version: '3.8'

services:
  rotator-db:
    container_name: rotator-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rotator
    ports:
      - "5432:5432"
    networks:
      some_network:
        aliases:
          - testdb.local

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      some_network:

  rotator:
#    build: ./build
    image: rotator:latest
    container_name: rotator-app
    restart: always
    ports:
      - "8186:8186"
    depends_on:
      - rotator-db
    networks:
      some_network:

networks:
  some_network:
    name: 'our_network'