server:
  host: "localhost"
  grpcPort: "8186"
  logLevel: "debug"

dsn:
  host: "127.0.0.1"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "rotator"
  ssl: "disable"

rmq:
  user: user
  password: pass
  host: "rabbitmq"
  port: "5672"
