name: Rotator pipeline

on:
  push:
    branches:
      - main

env:
  GO111MODULE: "on"

jobs:
  rotator-pipe:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21

      - name: Check out code
        uses: actions/checkout@v3

      - name: make lint
        run: make lint
        working-directory: .

      - name: make build
        run: make build
        working-directory: .

      - name: make test
        run: make test
        working-directory: .

      - name: make integration-tests
        run: make integration-tests
        working-directory: .